name: Main Server CI/CD

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

permissions:
  contents: read

jobs:
  validate-branch:
    if: startsWith(${{ github.head_ref }}, 'release-')
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          if [[ ! "$BRANCH_NAME" =~ ^release-[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            echo "$BRANCH_NAME does not match the pattern release-x.y.z"
            exit 1
          fi

  check-merged:
    needs: validate-branch
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check merged
        run: |
          echo 'The PR was merged'
  
  extract-version:
    needs: check-merged
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
          
      - name: extract version
        id: extract-version
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          echo $BRANCH_NAME
          echo $(echo $BRANCH_NAME | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "version=$(echo $BRANCH_NAME | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> "$GITHUB_OUTPUT"

          
